version: 2
jobs:
  node:
    working_directory: ~/capacitor-radar
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/capacitor-radar
          paths:
            - .
  android:
    working_directory: ~/capacitor-radar/example
    docker:
      - image: circleci/android:api-28-node
    steps:
      - checkout:
          path: ~/capacitor-radar
      - run: npm install
      - run: sudo npm install -g @ionic/cli
      - run: ionic build
      - run: npx cap sync
      - run: chown -R $USER:$USER android
      - run: cd android && ./gradlew assembleDebug
  ios:
    macos:
      xcode: "12.3.0"
    working_directory: ~/capacitor-radar/example
    steps:
      - checkout:
          path: ~/capacitor-radar
      - run: npm install
      - run: sudo npm install -g @ionic/cli
      - run: ionic build
      - run: npx cap sync
      - run: ionic capacitor run ios --target $(ionic capacitor run ios --list | grep -o -m 1 '[A-F0-9]\{8\}-[A-F0-9]\{4\}-[A-F0-9]\{4\}-[A-F0-9]\{4\}-[A-F0-9]\{12\}')
workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node